# Generated by Django 5.2.6 on 2026-02-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
